INSERT INTO public."Stores" ("StoreName") VALUES ('Cevahir');
INSERT INTO public."Stores" ("StoreName") VALUES ('Istiklal');
INSERT INTO public."Stores" ("StoreName") VALUES ('Kadikoy');

INSERT INTO public."Products" ("ProductName", "Cost", "SalesPrice") VALUES ('Shoes', 30, 120);
INSERT INTO public."Products" ("ProductName", "Cost", "SalesPrice") VALUES ('Tshirt', 10, 25);
INSERT INTO public."Products" ("ProductName", "Cost", "SalesPrice") VALUES ('Jacket', 5, 15);

INSERT INTO public."InventorySales" ("ProductId", "StoreId", "Date", "SalesQuantity", "Stock") VALUES (1, 1, '2017-03-04', 2, 23);
INSERT INTO public."InventorySales" ("ProductId", "StoreId", "Date", "SalesQuantity", "Stock") VALUES (1, 1, '2017-03-05', 4, 19);
INSERT INTO public."InventorySales" ("ProductId", "StoreId", "Date", "SalesQuantity", "Stock") VALUES (1, 1, '2017-03-06', 4, 15);
INSERT INTO public."InventorySales" ("ProductId", "StoreId", "Date", "SalesQuantity", "Stock") VALUES (1, 1, '2017-03-07', 0, 15);
INSERT INTO public."InventorySales" ("ProductId", "StoreId", "Date", "SalesQuantity", "Stock") VALUES (1, 1, '2017-03-08', 4, 11);
INSERT INTO public."InventorySales" ("ProductId", "StoreId", "Date", "SalesQuantity", "Stock") VALUES (1, 2, '2017-03-04', 2, 26);
INSERT INTO public."InventorySales" ("ProductId", "StoreId", "Date", "SalesQuantity", "Stock") VALUES (1, 2, '2017-03-05', 0, 23);
INSERT INTO public."InventorySales" ("ProductId", "StoreId", "Date", "SalesQuantity", "Stock") VALUES (1, 2, '2017-03-06', 0, 23);
INSERT INTO public."InventorySales" ("ProductId", "StoreId", "Date", "SalesQuantity", "Stock") VALUES (1, 2, '2017-03-07', 1, 25);
INSERT INTO public."InventorySales" ("ProductId", "StoreId", "Date", "SalesQuantity", "Stock") VALUES (1, 2, '2017-03-08', 0, 25);
INSERT INTO public."InventorySales" ("ProductId", "StoreId", "Date", "SalesQuantity", "Stock") VALUES (1, 3, '2017-03-04', 0, 15);
INSERT INTO public."InventorySales" ("ProductId", "StoreId", "Date", "SalesQuantity", "Stock") VALUES (1, 3, '2017-03-05', 0, 16);
INSERT INTO public."InventorySales" ("ProductId", "StoreId", "Date", "SalesQuantity", "Stock") VALUES (1, 3, '2017-03-06', 0, 16);
INSERT INTO public."InventorySales" ("ProductId", "StoreId", "Date", "SalesQuantity", "Stock") VALUES (1, 3, '2017-03-07', 2, 14);
INSERT INTO public."InventorySales" ("ProductId", "StoreId", "Date", "SalesQuantity", "Stock") VALUES (1, 3, '2017-03-08', 0, 14);
INSERT INTO public."InventorySales" ("ProductId", "StoreId", "Date", "SalesQuantity", "Stock") VALUES (3, 1, '2017-03-04', 2, 12);
INSERT INTO public."InventorySales" ("ProductId", "StoreId", "Date", "SalesQuantity", "Stock") VALUES (3, 1, '2017-03-05', 10, 2);
INSERT INTO public."InventorySales" ("ProductId", "StoreId", "Date", "SalesQuantity", "Stock") VALUES (3, 1, '2017-03-06', 0, 2);
INSERT INTO public."InventorySales" ("ProductId", "StoreId", "Date", "SalesQuantity", "Stock") VALUES (3, 1, '2017-03-07', 2, 0);
INSERT INTO public."InventorySales" ("ProductId", "StoreId", "Date", "SalesQuantity", "Stock") VALUES (3, 1, '2017-03-08', 0, 0);
INSERT INTO public."InventorySales" ("ProductId", "StoreId", "Date", "SalesQuantity", "Stock") VALUES (3, 2, '2017-03-04', 4, 5);
INSERT INTO public."InventorySales" ("ProductId", "StoreId", "Date", "SalesQuantity", "Stock") VALUES (3, 2, '2017-03-05', 3, 0);
INSERT INTO public."InventorySales" ("ProductId", "StoreId", "Date", "SalesQuantity", "Stock") VALUES (3, 2, '2017-03-06', 0, -1);
INSERT INTO public."InventorySales" ("ProductId", "StoreId", "Date", "SalesQuantity", "Stock") VALUES (3, 2, '2017-03-07', 0, 0);
INSERT INTO public."InventorySales" ("ProductId", "StoreId", "Date", "SalesQuantity", "Stock") VALUES (3, 2, '2017-03-08', 0, 0);
INSERT INTO public."InventorySales" ("ProductId", "StoreId", "Date", "SalesQuantity", "Stock") VALUES (3, 3, '2017-03-04', 0, 11);
INSERT INTO public."InventorySales" ("ProductId", "StoreId", "Date", "SalesQuantity", "Stock") VALUES (3, 3, '2017-03-05', 9, 2);
INSERT INTO public."InventorySales" ("ProductId", "StoreId", "Date", "SalesQuantity", "Stock") VALUES (3, 3, '2017-03-06', 3, -1);
INSERT INTO public."InventorySales" ("ProductId", "StoreId", "Date", "SalesQuantity", "Stock") VALUES (3, 3, '2017-03-07', 0, -1);
INSERT INTO public."InventorySales" ("ProductId", "StoreId", "Date", "SalesQuantity", "Stock") VALUES (3, 3, '2017-03-08', 1, -2);
INSERT INTO public."InventorySales" ("ProductId", "StoreId", "Date", "SalesQuantity", "Stock") VALUES (2, 1, '2017-03-04', 7, 28);
INSERT INTO public."InventorySales" ("ProductId", "StoreId", "Date", "SalesQuantity", "Stock") VALUES (2, 1, '2017-03-05', 5, 23);
INSERT INTO public."InventorySales" ("ProductId", "StoreId", "Date", "SalesQuantity", "Stock") VALUES (2, 1, '2017-03-06', 0, 23);
INSERT INTO public."InventorySales" ("ProductId", "StoreId", "Date", "SalesQuantity", "Stock") VALUES (2, 1, '2017-03-07', 3, 20);
INSERT INTO public."InventorySales" ("ProductId", "StoreId", "Date", "SalesQuantity", "Stock") VALUES (2, 1, '2017-03-08', 0, 20);
INSERT INTO public."InventorySales" ("ProductId", "StoreId", "Date", "SalesQuantity", "Stock") VALUES (2, 2, '2017-03-04', 5, 17);
INSERT INTO public."InventorySales" ("ProductId", "StoreId", "Date", "SalesQuantity", "Stock") VALUES (2, 2, '2017-03-05', 8, 9);
INSERT INTO public."InventorySales" ("ProductId", "StoreId", "Date", "SalesQuantity", "Stock") VALUES (2, 2, '2017-03-06', 9, 0);
INSERT INTO public."InventorySales" ("ProductId", "StoreId", "Date", "SalesQuantity", "Stock") VALUES (2, 2, '2017-03-07', 0, 0);
INSERT INTO public."InventorySales" ("ProductId", "StoreId", "Date", "SalesQuantity", "Stock") VALUES (2, 2, '2017-03-08', 0, 1);
INSERT INTO public."InventorySales" ("ProductId", "StoreId", "Date", "SalesQuantity", "Stock") VALUES (2, 3, '2017-03-04', 6, 54);
INSERT INTO public."InventorySales" ("ProductId", "StoreId", "Date", "SalesQuantity", "Stock") VALUES (2, 3, '2017-03-05', 3, 51);
INSERT INTO public."InventorySales" ("ProductId", "StoreId", "Date", "SalesQuantity", "Stock") VALUES (2, 3, '2017-03-06', 0, 51);
INSERT INTO public."InventorySales" ("ProductId", "StoreId", "Date", "SalesQuantity", "Stock") VALUES (2, 3, '2017-03-07', 0, 51);
INSERT INTO public."InventorySales" ("ProductId", "StoreId", "Date", "SalesQuantity", "Stock") VALUES (2, 3, '2017-03-08', 10, 41);
