version: '3.4'

networks:
  dev:
    driver: bridge
    
services:
  productservice:
    image: docker.io/library/productservice
    depends_on: 
      - "app_db"
    container_name: productservice-services
    ports:
      - "8088:80"
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=postgres;Server=app_db;Port=5432;Database=productservicedb;IntegratedSecurity=true;Pooling=true;
      - ASPNETCORE_URLS=http://+:80
    networks:
      - dev
  app_db:
    image: postgres:latest
    container_name: app_db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=productservicedb
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./docker/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      # copy the sql script to fill tables
      - ./docker/sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    networks:
      - dev

volumes:
    app_data:
      
      